package niteknightt.chess.lichessapi;

import com.google.gson.annotations.SerializedName;

public class LichessAccountEnums {

    public enum PerfsKey {
        @SerializedName("chess960")
        CHESS_960,
        @SerializedName("atomic")
        ATOMIC,
        @SerializedName("racingKings")
        RACING_KINGS,
        @SerializedName("ultraBullet")
        ULTRA_BULLET,
        @SerializedName("blitz")
        BLITZ,
        @SerializedName("kingOfTheHill")
        KING_OF_THE_HILL,
        @SerializedName("threeCheck")
        THREE_CHECK,
        @SerializedName("antichess")
        ANTICHESS,
        @SerializedName("crazyhouse")
        CRAZY_HOUSE,
        @SerializedName("bullet")
        BULLET,
        @SerializedName("correspondence")
        CORRESPONDENCE,
        @SerializedName("horde")
        HORDE,
        @SerializedName("puzzle")
        PUZZLE,
        @SerializedName("classical")
        CLASSICAL,
        @SerializedName("rapid")
        RAPID,
        @SerializedName("storm")
        STORM,
        @SerializedName("racer")
        RACER,
        @SerializedName("streak")
        STREAK
    }

    public enum Title {
        @SerializedName("GM")
        GM,
        @SerializedName("WGM")
        WGM,
        @SerializedName("IM")
        IM,
        @SerializedName("WIM")
        WIM,
        @SerializedName("FM")
        FM,
        @SerializedName("WFM")
        WFM,
        @SerializedName("NM")
        NM,
        @SerializedName("CM")
        CM,
        @SerializedName("WCM")
        WCM,
        @SerializedName("WNM")
        WNM,
        @SerializedName("LM")
        LM,
        @SerializedName("BOT")
        BOT
    }

    public enum CountType {
        @SerializedName("all")
        ALL,
        @SerializedName("rated")
        RATED,
        @SerializedName("ai")
        AI,
        @SerializedName("draw")
        DRAW,
        @SerializedName("drawH")
        DRAW_H,
        @SerializedName("loss")
        LOSS,
        @SerializedName("lossH")
        LOSS_H,
        @SerializedName("win")
        WIN,
        @SerializedName("winH")
        WIN_H,
        @SerializedName("bookmark")
        BOOKMARK,
        @SerializedName("playing")
        PLAYING,
        @SerializedName("import")
        IMPORT,
        @SerializedName("me")
        ME
    }

    public enum Theme {
        @SerializedName("blue")
        BLUE,
        @SerializedName("blue2")
        BLUE2,
        @SerializedName("blue3")
        BLUE3,
        @SerializedName("blue-marble")
        BLUE_MARBLE,
        @SerializedName("canvas")
        CANVAS,
        @SerializedName("wood")
        WOOD,
        @SerializedName("wood2")
        WOOD2,
        @SerializedName("wood3")
        WOOD3,
        @SerializedName("wood4")
        WOOD4,
        @SerializedName("maple")
        MAPLE,
        @SerializedName("maple2")
        MAPLE2,
        @SerializedName("brown")
        BROWN,
        @SerializedName("leather")
        LEATHER,
        @SerializedName("green")
        GREEN,
        @SerializedName("marble")
        MARBLE,
        @SerializedName("green-plastic")
        GREEN_PLASTIC,
        @SerializedName("grey")
        GREY,
        @SerializedName("metal")
        METAL,
        @SerializedName("olive")
        OLIVE,
        @SerializedName("newspaper")
        NEWSPAPER,
        @SerializedName("purple")
        PURPLE,
        @SerializedName("purple-diag")
        PURPLE_DIAG,
        @SerializedName("pink")
        PINK,
        @SerializedName("ic")
        IC
    }

    public enum Theme3D {
        @SerializedName("Black-White-Aluminium")
        BLACK_WHITE_ALUMINIUM,
        @SerializedName("Brushed-Aluminium")
        BRUSHED_ALUMINIUM,
        @SerializedName("China-Blue")
        CHINA_BLUE,
        @SerializedName("China-Green")
        CHINA_GREEN,
        @SerializedName("China-Grey")
        CHINA_GREY,
        @SerializedName("China-Scarlet")
        CHINA_SCARLET,
        @SerializedName("Classic-Blue")
        CLASSIC_BLUE,
        @SerializedName("Gold-Silver")
        GOLD_SILVER,
        @SerializedName("Light-Wood")
        LIGHT_WOOD,
        @SerializedName("Power-Coated")
        POWER_COATED,
        @SerializedName("Rosewood")
        ROSEWOOD,
        @SerializedName("Marble")
        MARBLE,
        @SerializedName("Wax")
        WAX,
        @SerializedName("Jade")
        JADE,
        @SerializedName("Woodi")
        WOODI
    }

    public enum PieceSet {
        @SerializedName("cburnett")
        CHURNETT,
        @SerializedName("merida")
        MERIDA,
        @SerializedName("alpha")
        ALPHA,
        @SerializedName("pirouetti")
        PIROUETTI,
        @SerializedName("chessnut")
        CHESSNUT,
        @SerializedName("chess7")
        CHESS7,
        @SerializedName("reillycraig")
        REILLYCRAIG,
        @SerializedName("companion")
        COMPANION,
        @SerializedName("riohacha")
        RIOHACHA,
        @SerializedName("kosal")
        KOSAL,
        @SerializedName("leipzig")
        LEIPZIG,
        @SerializedName("fantasy")
        FANTASY,
        @SerializedName("spatial")
        SPATIAL,
        @SerializedName("california")
        CALIFORNIA,
        @SerializedName("pixel")
        PIXEL,
        @SerializedName("maestro")
        MAESTRO,
        @SerializedName("fresca")
        FRESCO,
        @SerializedName("cardinal")
        CARDINAL,
        @SerializedName("gioco")
        GIOCO,
        @SerializedName("tatiana")
        TATIANA,
        @SerializedName("staunty")
        STAUNTY,
        @SerializedName("governor")
        GOVERNOR,
        @SerializedName("dubrovny")
        DUBROVNY,
        @SerializedName("icpieces")
        ICPIECES,
        @SerializedName("shapes")
        SHAPES,
        @SerializedName("letter")
        LETTER
    }

    public enum PieceSet3D {
        @SerializedName("Basic")
        BASIC,
        @SerializedName("Wood")
        WOOD,
        @SerializedName("Metal")
        METAL,
        @SerializedName("RedVBlue")
        RED_V_BLUE,
        @SerializedName("ModernJade")
        MODERN_JADE,
        @SerializedName("ModernWood")
        MODERN_WOOD,
        @SerializedName("Glass")
        GLASS,
        @SerializedName("Trimmed")
        TRIMMED,
        @SerializedName("Experimental")
        EXPERIMENTAL,
        @SerializedName("Staunton")
        STAUNTON,
        @SerializedName("CubesAndPi")
        CUBES_AND_PI
    }

    public enum SoundSet {
        @SerializedName("silent")
        SILENT,
        @SerializedName("standard")
        STANDARD,
        @SerializedName("piano")
        PIANO,
        @SerializedName("nes")
        NES,
        @SerializedName("sfx")
        SFX,
        @SerializedName("futuristic")
        FUTURISTIC,
        @SerializedName("robot")
        ROBOT,
        @SerializedName("music")
        MUSIC,
        @SerializedName("speech")
        SPEECH
    }

    public enum TimelineEntryType {
        @SerializedName("stream-start")
        STREAM_START,
        @SerializedName("ublog-post-like")
        UBLOG_POST_LIKE,
        @SerializedName("plan-renew")
        PLAN_RENEW,
        @SerializedName("plan-start")
        PLAN_START,
        @SerializedName("study-like")
        STUDY_LIKE,
        @SerializedName("simul-join")
        SIMUL_JOIN,
        @SerializedName("simul-create")
        SIMUL_CREATE,
        @SerializedName("game-end")
        GAME_END,
        @SerializedName("tour-join")
        TOUR_JOIN,
        @SerializedName("ublog-post")
        UBLOG_POST,
        @SerializedName("blog-post")
        BLOG_POST,
        @SerializedName("forum-post")
        FORUM_POST,
        @SerializedName("team-create")
        TEAM_CREATE,
        @SerializedName("team-join")
        TEAM_JOIN,
        @SerializedName("follow")
        FOLLOW
    }

}
